# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
class CentOsInstallers < VagrantVbguest::Installers::RedHat
  def install(opts=nil, &block)
    communicate.sudo('yum -y install https://rpmfind.net/linux/centos/7.5.1804/updates/x86_64/Packages/kernel-devel-3.10.0-862.9.1.el7.x86_64.rpm', opts, &block)
    super
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vbguest.installer = CentOsInstallers

  config.vm.network :forwarded_port, guest: 5601, host: 5601
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  config.vm.synced_folder "../data", "/vagrant_data"

  config.omnibus.chef_version = "12.10.24"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
    chef.add_recipe "yum"
    chef.add_recipe "yum-epel"
    chef.add_recipe "java"
    chef.add_recipe "ruby"
    chef.add_recipe "jruby"
    chef.add_recipe "logstash-rpm"
    chef.add_recipe "vim"
  end
end
